### ISSUE TITLE
Needs to be updated with the latest GO driver 1.11 from Dec 2020

### ISSUE THREAD

**Issue by verticacrossman** [vertica/vertica-grafana-datasource#11]
Need to update the GO driver in the plugin to the latest 1.11 release from Dec 2020. That release includes bug fixes, performance enhancements, and support for the native load balancing. It was added in during the attempt to merge framework updates in May 2020 but those got reverted, and along with them the load balancing was lost.

**Comment by tanvipise** [comment]
Go driver is updated and tested with v1.6.2
