### ISSUE TITLE
Grafana offers an elegant way to create dashboard variables where user sees/selects from friendly “__text”, but queries operate on the non-displayed “__value”

### ISSUE THREAD

**Issue by tanvipise** [vertica/vertica-grafana-datasource#13]
Customer reported:

-  Example dashboard variable from query: select  clientname as __text, clientid as __value from CLIENT
-  Yields key:value pairs like  GUS:001, PHREAD:003, … XXX:nnn
-  User sees GUS, PHREADE, … XXX (in dropdown selector and when the variable is referenced in panel titles)
-  Vertica query would reference 001, 003, …. Nnn
-  Your unsigned plugin supported this, but signed  version errors with Error [22V02] invalid input syntax for integer: GUS – rather than use 001

**Comment by bryanherger** [comment]
Please see commit https://github.com/bryanherger/vertica-grafana-datasource/commit/7a374861932c4c94e87e2363f2ed94ed797c3349 for a way to fix this issue.  I can submit a new PR after my previous is merged.

**Comment by tanvipise** [comment]
Resolved in the latest release v2.0.1. Thank you @bryanherger for your contributions.

**Comment by tanvipise** [comment]
Thanks Bryan!

**Comment by nicolaerosia** [comment]
Is this fixed?

**Comment by tanvipise** [comment]
Yes, it is fixed.
