### ISSUE TITLE
timeFrom and timeTo macros fail when used in function

### ISSUE THREAD

**Issue by prokopenkopn** [vertica/vertica-grafana-datasource#16]
This query: "**SELECT $__timeFrom()**" - works OK.
But this: "**SELECT LEFT($__timeFrom(), 19)**" - fails with error: "_macro __timeFrom should have no arguments_"

In grafana.log:
_t=2021-11-09T10:49:21+0300 lvl=info msg=QueryData logger=plugins.backend pluginId=vertica-grafana-datasource timeR=2021-11-09T04:50:32.303+03:00
t=2021-11-09T10:49:21+0300 lvl=eror msg="Error while replacing the string submatches: macro __timeFrom should have no arguments" logger=plugins.backend pluginId=vertica-grafana-datasource
t=2021-11-09T10:49:21+0300 lvl=eror msg="Error while sanitizing the query: macro __timeFrom should have no arguments" logger=plugins.backend pluginId=vertica-grafana-datasource_

**Comment by oBoMBaYo** [comment]
Any updates, We also faced the same issue.

**Comment by jayhyuk** [comment]
Me too

**Comment by tanvipise** [comment]
The variable is interpolated before the query is sent to the datasource. So in this case the $__timeFrom needs to be resolved prior to passing it inside the LEFT function. Please refer this [link](https://grafana.com/docs/grafana/latest/variables/syntax/) for details.
