### ISSUE TITLE
Datasource error Connection: parse....

### ISSUE THREAD

**Issue by m5altamiranoroldan** [vertica/vertica-grafana-datasource#19]
Hi guys, i´m a new user for this vertica plugin, after the installation process i get this error when try to test teh connection to the Vertica DB, even after set the correct credentilas and connection method: 

logger=plugin.vertica-grafana-datasource t=2022-06-10T11:12:42.83-0500 lvl=info msg="CheckHealth :connection: parse \"vertica://**username:password**\": invalid port \":**password**\" after host"

Note. Bolded text were replaced, original erros shown user and password seted.

Can you please help me with thath?

thanks in advance!

**Comment by tanvipise** [comment]
Hi, 

The connection string seems to be incorrect from the detail you provided. You can use this instead and let us know if you still face the error: **vertica://host:port/databasename**

Also, make sure that there is a port number(5433) included when you input the hostname
![image](https://user-images.githubusercontent.com/56138955/174877713-0ac620c6-562c-4ec7-9659-3e1268acb21a.png)

Please provide a detailed log if the above solution doesn't resolve the issue.

Thanks!
