### ISSUE TITLE
Vertica cluster: connection load balancing not possible

### ISSUE THREAD

**Issue by ankitdm24** [vertica/vertica-grafana-datasource#25]
Hi,

Currently there doesn't seem to be a way to specify multiple Vertica hosts that are part of the cluster. With a single hostname field, the connection will fail if the configured host goes down, even if rest of the hosts in the cluster are running. Is that understanding correct? Or is there an option to provide a comma separated list of hostnames in the 'Host' field?

The issue I mention is different from the flag "Use Connection Load Balancing", which still relies on the configured host being UP.

Thanks
-Ankit

**Comment by tanvipise** [comment]
Hi Ankit,

Thanks for reaching out. The connection load balancer in the plugin doesn't support fail safety. There is a backup server node feature in [Vertica ](https://github.com/vertica/vertica-sql-go#creating-a-connection) that will give the desired behavior, but the plugin doesn't currently support adding parameters to the connection string. 

We can add it to our list of future enhancements or feel free to create a Pull Request if you'd like to contribute.

Thanks,
Tanvi

**Comment by ankitdm24** [comment]
Hi Tanvi,

Thanks for your response, and adding this feature to your list of future enhancements. 

Thanks
-Ankit
