### ISSUE TITLE
The plugin doesn't read the timestamp correctly

### ISSUE THREAD

**Issue by ankitdm24** [vertica/vertica-grafana-datasource#26]
I have a table in my Vertica that stores cpu utilization metrics over time. Here is a snapshot of the data from my database using the query "SELECT  timestamp_tz,  cpu_util_pct_avg  FROM  opsb_sysinfra_node_1h  ORDER BY cpu_util_pct_avg":

![image](https://user-images.githubusercontent.com/24474880/188813465-384e8ffd-d92b-4fac-8cd0-0c0cc34bc9ec.png)

However, in Grafana all of the timestamps are interpreted as 31-Aug-1754 04:37:09.129, while they are different timestamps in the DB and from this year. See the snapshot from Grafana explore using the query: "SELECT  timestamp_tz,  cpu_util_pct_avg  FROM  opsb_sysinfra_node_1h  ORDER BY cpu_util_pct_avg"
![image](https://user-images.githubusercontent.com/24474880/188814128-ace4f6c3-604d-4127-81bd-1502a53827c7.png)

The column timestamp_tz is of datatype Timestamp.

Any insight on what could be the issue here? I am a newbie to Grafana, so let me know if I'm doing something wrong.

Thanks
-Ankit

**Comment by ankitdm24** [comment]
BTW, I am using v 2.0.2

**Comment by tanvipise** [comment]
Hi Ankit, 

I tried to reproduce the issue and it gave me no such errors reading the timestamp column. You might want to upgrade the Grafana version and restart Grafana.

If it still doesn't work, you can try to use the macros in your query like:
SELECT $__time(start_time), average_cpu_usage_percent FROM v_monitor.cpu_usage;

![image](https://user-images.githubusercontent.com/56138955/194408073-e6526893-674e-428d-a506-6c2d1f1fd9c5.png)

Let me know of any issues.
Thanks!
