### ISSUE TITLE
Question: Does this plugin support IPV6 Databases connection

### ISSUE THREAD

**Issue by vBitza** [vertica/vertica-grafana-datasource#32]
Hi there, we've run into a problem while trying to use this Plugin with a Database running in an IPV6 Environment. I couldn't find it anywhere in the documentation if this is actually supported or not and wanted to check with you aswell.

If we give the host as is it doesn't seem to be able to connect, an usually in IPV6 you need the extra set of square brackets, while doing it we get the following error:

 
![image](https://user-images.githubusercontent.com/37511091/210370023-4ebfbf10-9f73-4964-8263-dc0caa79a902.png)

**Comment by vertigo15** [comment]
HI,
I encountered the same problem. It is working fine in 2.0.1 but not in 2.0.3

**Comment by sitingren** [comment]
This is a regression in its dependency (vertica/vertica-sql-go). Please use version <=2.0.2 for now and wait for the next release. Sorry for the inconvenience and thank you.

**Comment by vBitza** [comment]
Thanks for the reply! 

This can be closed in this case or marked as an action item to update the dependency which caused the regression, up to you.

**Comment by vertigo15** [comment]
Thank you.

**Comment by tanvipise** [comment]
Updated and fixed in v2.1.0 of the plugin.
