### ISSUE TITLE
Not able to create Vertica Data Source on Windows Grafana

### ISSUE THREAD

**Issue by das0110** [vertica/vertica-grafana-datasource#33]
I am using grafana-enterprise-9.3.6 on Windows and I have downloaded vertica-grafana-datasource-2.0.3   version and ensured the extracted to "C:\Program Files\GrafanaLabs\grafana\public\app\plugins\datasource\vertica-grafana-datasource" Path.

While i am trying to add the Vertica Data source am getting below Error:
"_**Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/vertica-grafana-datasource/module Loading app/plugins/datasource/vertica-grafana-datasource/module**_
**_Data Source Error_**"

I have tried going through the Forums and nothing helped me, could someone guide me on how to proceed on this issue.

Please note am facing the same issue after downgrading the plugin to vertica-grafana-datasource-2.0.2 as well

Thanks in Advance!!
Regards,
Das

**Comment by tanvipise** [comment]
Hello Das,

You might want to download and install the plugin from the Grafana plugins page and don't forget to remove the earlier one by uninstalling it.
![image](https://user-images.githubusercontent.com/56138955/216631270-986986eb-77ba-45a0-b55a-55ffe07afbab.png)

The other way to download is to get the .zip file of the distribution from our GitHub releases. Not sure if you downloaded the source code, it is only for dev purposes and will be an unsigned version.

Let me know if that helped!

Thanks,
Tanvi

**Comment by das0110** [comment]
Hi Tanvi,

Appreciate your Support !!

That's a great help, previously I have tried downloaded the Plugin via CLI & from GIT repositories but that didn't work. As you said i have downloaded from plugin tab that worked.

Now am facing the below mentioned issue while trying to configure the connection:

**parse "vertica://vertica:Report": invalid port ":Report" after host**

![image](https://user-images.githubusercontent.com/124345876/216753344-339f304a-8794-47ff-b54a-7a2f052ff9af.png)

Can you please help me understand where I went wrong? 

Regards,
Das

**Comment by tanvipise** [comment]
#34 Solution provided

**Comment by das0110** [comment]
Hi Tanvipise,

Despite my efforts, I'm still encountering the same problem. I have verified that the hostname or IP address I'm entering, along with the port, is correct. I can connect to the database from my local machine using tools like DBVisualizer. Could this be due to a driver configuration issue? Can you please provide some guidance?

Thanks for your Support!!

Regards,
Das

**Comment by tanvipise** [comment]
Could you provide the Grafana and Vertica log files while you test the connection? We can try to see where exactly it breaks.

**Comment by das0110** [comment]
H Tanvipise,

I am able to see below mentioned log entires in Grafana logs:

logger=plugin.vertica-grafana-datasource t=2023-02-10T16:53:14.4945265+05:30 level=info msg="newDataSourceInstance: new instance of datasource created: Vertica"
logger=plugin.vertica-grafana-datasource t=2023-02-10T16:53:14.4945265+05:30 level=info msg="CheckHealth :connection: parse \"vertica://vertica:Report\": invalid port \":Report\" after host"
logger=context userId=1 orgId=1 uname=admin t=2023-02-10T16:53:14.4955548+05:30 level=info msg="Request Completed" method=GET path=/api/datasources/1/health status=400 remote_addr=[::1] time_ms=4 duration=4.2775ms size=102 referer=http://localhost:3000/datasources/edit/RtzoXp04z handler=/api/datasources/:id/health


& below mentioned is the configuration i am trying to test:

![image](https://user-images.githubusercontent.com/124345876/218081088-2fbb54cf-9033-44c9-a4af-9af8ac21c524.png)


I have ensured that i am entering correct Hostname or IP Address and credentials. Also am able to login with out any issues from other SQL Client tools to the above specified Vertica Host.

Regards,
Gopi

**Comment by verticacrossman** [comment]
Das,
I've been discussing this with Tanvi. Odd error that there isn't much on in the various Grafana sights. One suggestion would be to activate debug logging to see if it provides more hints in the grafana.log.

Edit your grafana config file (usually /etc/grafana/grafana.ini on Linux)
Search for "debug" and it should land you in the folowing section

#################################### Logging ##########################
log
(Either "console", "file", "syslog". Default is console and  file)
(Use space to separate multiple modes, e.g. "console file")
;mode = console file
(Either "debug", "info", "warn", "error", "critical", default is "info")
;level = debug

Uncomment the mode line so console and file are active
Uncomment and edit the level line as needed to set to debug
Restart the grafana server
Rerun the Save and Test
See if there is any additional info posted to the console. Also check the grafana.log

If additional info please forward. Make sure to reset the logging config to it's default afterwards.

**Comment by verticacrossman** [comment]
PS also try creating a new datasource in case the existing one is somehow corrupted
