### ISSUE TITLE
Vertica Data Source Test Connection Fails

### ISSUE THREAD

**Issue by das0110** [vertica/vertica-grafana-datasource#34]
Hi Tanvi,

Appreciate your Support !!

I am using grafana-enterprise-9.3.6 on Windows & am facing the below mentioned issue while trying to configure Vertica the connection:

**parse "vertica://vertica:Report": invalid port ":Report" after host**

![image](https://user-images.githubusercontent.com/124345876/216888241-0579018f-c80d-4777-a988-029af47d49ff.png)

Can you please help me understand where I went wrong?

Regards,
Das

**Comment by tanvipise** [comment]
Hi,

You need to make sure that the hostname/IP is in the correct format followed by a colon with the port number(5433)- eg. 10.20.30.40:5433

What is the IP or hostname that you are trying to use?

**Comment by tanvipise** [comment]
If your database password contains '#' in it, you will need to use escape characters i.e., replace '#' with '%23'.
https://github.com/vertica/vertica-sql-go/issues/158
