### ISSUE TITLE
Does not work on Apple M1 Pro

### ISSUE THREAD

**Issue by junsongzhao** [vertica/vertica-grafana-datasource#41]
The plugin does not work on Apple M1 Pro with the following message: 
 level=error msg="Could not start plugin" pluginId=vertica-grafana-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource/gpx_vertica-grafana-plugin_darwin_arm64: no such file or directory"

**Comment by tanvipise** [comment]
Hi,
Did you install the plugin via the plugin source code(which is used for development) or did you install the plugin through Grafana?

If you are using the source code, you won't have the distribution file as suggested in your error. You will have to manually build the plugin with the given steps in the README file to set up the dev environment.

Let me know if this helps!
