### ISSUE TITLE
Does not work on Apple M2 Pro

### ISSUE THREAD

**Issue by Zeevbd** [vertica/vertica-grafana-datasource#44]
Hi, 
i have raised a ticket on a vertica plugin compatibility for M2 Apple Chipset.
the suggestion from tech support to raise an issue in the GitHub Rep:

have tried the solution given for the M1 Apple Chipset but it seems to not work: 
https://github.com/vertica/vertica-grafana-datasource/issues/41

#################################################################
Response from : Grafana Tech Support suggested to open an issue under GitHub repo
#################################################################
"The error seems to be related to the plugin compatibility, and it is recommended to raise the issue in the GitHub [repo](https://github.com/vertica/vertica-grafana-datasource/issues) and please let them know you already tried the suggestion for M1."
  (Jay T. Support Engineer Grafana Labs)

please assist

**Comment by tanvipise** [comment]
Hi, 
Can you please explain the steps you followed to set up the plugin? I am assuming it should be something related to the installation that went wrong. Let me know, I can try to reproduce it.

**Comment by Zeevbd** [comment]
Certainly,

So i tried building up the plugin, but ended up with no success


steps i used:
Used the Command: git clone https://github.com/vertica/vertica-grafana-datasource
yarn is installed : yarn run v1.22.19

warning package.json: "dependencies" has dependency "react-autosuggest" with range "^10.1.0" that collides with a dependency in "devDependencies" of the same name with version "^9.4.3"

conflict on the versions under packages.json

**so i have aligned the autosuggest on the file:**

"@types/react-autosuggest": "^10.1.6",

"ts-jest": "26.4.4",

"ts-loader": "8.0.4",

"tslib": "^2.2.0",

"typescript": "4.1.2"

},
"resolutions": {
"rxjs": "6.6.3"
},
"engines": {
"node": ">=14"
},
"dependencies": {
"@emotion/css": "^11.10.5",
"@types/react-autosuggest": "^10.1.6",
"@types/react-virtualized-auto-sizer": "^1.0.1",
"ace-builds": "^1.15.2",
"brace": "^0.11.1",
"grafana-data": "^2.0.1",
"react-ace": "^10.1.0",
"react-autosuggest": "^10.1.0",
"react-awesome-query-builder": "^5.4.1",
"react-monaco-editor": "^0.51.0",
"react-use": "^17.4.0",
"react-virtualized-auto-sizer": "^1.0.7",
"yarn": "^1.22.19"
}

after aligning manually the Version expectations results then showed the following:

$ grafana-toolkit plugin:build
No longer supported. Use grafana create-plugin https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

hope this elaborates the process

**Comment by tanvipise** [comment]
Thanks for the info. I am trying to reproduce this and will update you soon. All the tests that we have done till now are based on Linux and Windows environments. 

Have you tried installing the plugin from Grafana interface itself instead of building the plugin? Does the Grafana plugins list show the plugin in there? 
![image](https://github.com/vertica/vertica-grafana-datasource/assets/56138955/aed2ec04-6952-4222-b057-5c6ba6cd0b25)

Usually building the plugin will need a complete environment setup that includes Go, Mage, etc as mentioned in the Readme. 

Maybe try uninstalling and deleting the plugin folder through the grafana-cli command:
`grafana-cli plugins remove vertica-grafana-datasource`

Another approach is to verify the plugin id. It should specify the exact name - `vertica-grafana-datasource`

**Comment by Zeevbd** [comment]
Thanks for the update,
i did both ways:
- installed the plugin through the Grafana interface and restarted the service
although the plugin shown as installed on the interface the grafana log showed:

logger=secrets t=2023-06-24T23:43:14.268113+03:00 level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=local.finder t=2023-06-24T23:43:14.326493+03:00 level=warn msg="Skipping finding plugins as directory does not exist" path=/opt/homebrew/opt/grafana/share/grafana/plugins-bundled logger=plugin.loader t=2023-06-24T23:43:14.379145+03:00 level=info msg="Plugin registered" pluginID=vertica-grafana-datasource
logger=plugin.loader t=2023-06-24T23:43:14.380466+03:00 level=error msg="Could not start plugin" pluginId=vertica-grafana-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource/gpx_vertica-grafana-plugin_darwin_arm64: **no such file or directory"**

a note worth mentioning:
have installed grafana via brew

restarted the grafana service: brew services restart grafana

Thanks.
Ze'ev

**Comment by tanvipise** [comment]
Hi,

It worked for me with no issues after reproducing from your steps provided. The plugin path in your case is `path=/opt/homebrew/opt/grafana/share/grafana/plugins-bundled` whereas in my system it shows `/usr/local/var/lib/grafana/plugins/vertica-grafana-datasource`

Can you try to check the config file - grafana.ini file to see if the plugin's path has been changed?
You’ll find the config file in `/usr/local/etc/grafana/grafana.ini`. It should be commented (with the semicolon, ;), in which case the default path will be used. You can also try uncommenting the line and set the directory to one that you decide.

**Comment by Zeevbd** [comment]
Thanks for the comments, i tried your suggestions:

so the grafana.ini file that is loaded by grafana resides under:
/opt/homebrew/etc/grafana/grafana.ini

(took out the semicolon ;)

# Directory where grafana will automatically scan and look for plugins
plugins = /opt/homebrew/var/lib/grafana/plugins

restarted the service:

❯ brew services restart grafana
Stopping `grafana`... (might take a while)
==> Successfully stopped `grafana` (label: homebrew.mxcl.grafana)
==> Successfully started `grafana` (label: homebrew.mxcl.grafana)
/opt/homebrew/var/plugins stable ❯


opened the admin/settings: to see that plugins folder is updated:

<img width="682" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/5eb4b37f-9779-4fb7-9e86-735a54562997">

vertica plugins location directory:
❯ sudo find / -name vertica-grafana-datasource -print 2>/dev/null
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource


**log file showed after the restart:**
logger=plugin.loader t=2023-07-18T09:07:38.26076+03:00 level=info msg="Plugin registered" pluginID=vertica-grafana-datasource
logger=plugin.loader t=2023-07-18T09:07:38.263912+03:00 level=error msg="Could not start plugin" pluginId=vertica-grafana-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource/gpx_vertica-grafana-plugin_darwin_arm64: no such file or directory"


as can see, directory is not empty:

❯ pwd
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource
❯ ls -lrt
total 125128
-rw-r--r--@  1 zeev.bd  admin      3007 Jul 18 07:46 MANIFEST.txt
-rw-r--r--@  1 zeev.bd  admin      1733 Jul 18 07:46 plugin.json
-rwxr-xr-x@  1 zeev.bd  admin  11796480 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_arm64
-rwxr-xr-x@  1 zeev.bd  admin  12378624 Jul 18 07:46 gpx_vertica-grafana-plugin_windows_amd64.exe
-rw-r--r--@  1 zeev.bd  admin     11357 Jul 18 07:46 LICENSE
-rw-r--r--@  1 zeev.bd  admin    541886 Jul 18 07:46 module.js
-rwxr-xr-x@  1 zeev.bd  admin  13230752 Jul 18 07:46 gpx_vertica-grafana-plugin_darwin_amd64
drwxr-xr-x@ 13 zeev.bd  admin       416 Jul 18 07:46 img
-rwxr-xr-x@  1 zeev.bd  admin  12374016 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_amd64
-rw-r--r--@  1 zeev.bd  admin   1828149 Jul 18 07:46 module.js.map
-rwxr-xr-x@  1 zeev.bd  admin  11862016 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_arm
-rw-r--r--@  1 zeev.bd  admin     13142 Jul 18 07:46 README.md
-rw-r--r--@  1 zeev.bd  admin      2510 Jul 18 07:46 module.js.LICENSE.txt


not sure what is missing or not working for me...

**Comment by Zeevbd** [comment]
one more thing to add:
have installed another plugin named CSV

<img width="1201" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/f019fdcc-0267-472a-9bf5-fa254c5ab29a">

Restarted the Grafana Service:

the log does not write any failure with the CSV plugin 

**cat /opt/homebrew/var/log/grafana-stdout.log**

logger=plugin.loader t=2023-07-18T12:40:26.106968+03:00 level=info msg="Plugin registered" pluginID=marcusolsson-csv-datasource
logger=plugin.loader t=2023-07-18T12:40:26.124549+03:00 level=info msg="Plugin registered" pluginID=vertica-grafana-datasource
logger=plugin.loader t=2023-07-18T12:40:26.12604+03:00 level=error msg="Could not start plugin" pluginId=vertica-grafana-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource/gpx_vertica-grafana-plugin_darwin_arm64: no such file or directory"

both plugin directories reside under same folder:

❯ pwd
/opt/homebrew/var/lib/grafana/plugins
❯ ls -lrt
total 0
drwxr-xr-x@ 15 zeev.bd  admin  480 Jul 18 07:46 vertica-grafana-datasource
drwxr-xr-x@ 13 zeev.bd  admin  416 Jul 18 12:29 marcusolsson-csv-datasource


seems the plugin path is correctly defined
HOWEVER, i have no idea why Grafana would not find the file nor directory. of the vertica plugin ..


Please asist
 Ze'ev

**Comment by Zeevbd** [comment]
o.k
seems like a missing file under the plugin directory:
as the grafana server is looking for the file: gpx_vertica-grafana-plugin_darwin_arm64

while directory does not contain **arm64** file but: gpx_vertica-grafana-plugin_darwin_amd64

so the Apple M2 looks for the arm64 file that is not present under the plugin directory...

seems that an **arm64**  compilation file  is needed to overcome the problem

**Comment by tanvipise** [comment]
The distribution list is generated using the Grafana toolkit and published during the plugin release. We don't change the manifest as the toolkit is used to build the package of the plugin.

Did you try installing the plugin through the interface once again after you changed the grafana.ini file and the directory paths? Also, don't forget to restart the service.

I am trying to get some more details on this as well.

**Comment by Zeevbd** [comment]
i did install the plugin through the interface after changing the grafana.ini...
to my opinion the main reason for the failure is that Grafana plugin looks for a file that does not exist in the plugin folder:

 Grafana looks for: **gpx_vertica-grafana-plugin_darwin_arm64**  that does not exist
and that is the main cause for the failure.

what is the entity responsible of creating the files under plugin folder?
as can see down below the file: **gpx_vertica-grafana-plugin_darwin_arm64**  does not exist

❯ pwd
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource
❯ ls -lrt
total 125128
-rw-r--r--@ 1 zeev.bd admin 3007 Jul 18 07:46 MANIFEST.txt
-rw-r--r--@ 1 zeev.bd admin 1733 Jul 18 07:46 plugin.json
-rwxr-xr-x@ 1 zeev.bd admin 11796480 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_arm64
-rwxr-xr-x@ 1 zeev.bd admin 12378624 Jul 18 07:46 gpx_vertica-grafana-plugin_windows_amd64.exe
-rw-r--r--@ 1 zeev.bd admin 11357 Jul 18 07:46 LICENSE
-rw-r--r--@ 1 zeev.bd admin 541886 Jul 18 07:46 module.js
-rwxr-xr-x@ 1 zeev.bd admin 13230752 Jul 18 07:46 gpx_vertica-grafana-plugin_darwin_amd64
drwxr-xr-x@ 13 zeev.bd admin 416 Jul 18 07:46 img
-rwxr-xr-x@ 1 zeev.bd admin 12374016 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_amd64
-rw-r--r--@ 1 zeev.bd admin 1828149 Jul 18 07:46 module.js.map
-rwxr-xr-x@ 1 zeev.bd admin 11862016 Jul 18 07:46 gpx_vertica-grafana-plugin_linux_arm
-rw-r--r--@ 1 zeev.bd admin 13142 Jul 18 07:46 README.md
-rw-r--r--@ 1 zeev.bd admin 2510 Jul 18 07:46 module.js.LICENSE.txt

**Comment by tanvipise** [comment]
I am working with the Grafana plugin team to resolve this issue as the arm64 file was not generated by the Grafana toolkit. Will let you know about the update soon.

**Comment by Zeevbd** [comment]
perfect !!!
thank you very much for the help

**Comment by tanvipise** [comment]
Hi, 

While reviewing the documentation, I found that the 'nvm' only supports arm packages after v16 and our plugin is built using v14.17.6. See below:
For Macs with the M1 chip, node started offering arm64 arch Darwin packages since v16.0.0 and experimental arm64 support when compiling from source since v14.17.0. If you are facing issues installing node using nvm, you may want to update to one of those versions or later. [nvm install and update](https://github.com/nvm-sh/nvm#installing-and-updating)

Grafana will no longer support the plugin built using the toolkit anymore. I am currently working on the migration from the toolkit. I will be updating the plugin with the latest updates soon and will include the arm64 distribution file for MacOS. Until then, I would advise you to upgrade your environment with 'nvm v>16'.

**Comment by Zeevbd** [comment]
thanks,
so i did install the nvm:

<img width="258" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/abc86078-73e3-4314-baf6-52f143fd0341">

the nvm installation added a new file:  **node-v16.20.1-darwin-arm64.tar.xz**

<img width="927" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/b221cca5-a1bf-4694-898f-52e9074960d8">


i have extracted the directory: but i am not sure how to compile it to the missing plugin: 
**_gpx_vertica-grafana-plugin_darwin_arm64_**

<img width="632" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/a5442dad-2df8-45ce-9274-b80d58046aa4">


any way to move forward on my side?
or will it be for the best to wait for your updated plugin that will include the arm64 distribution?


Thanks for you great support.
Ze'ev

**Comment by tanvipise** [comment]
You will have to build the plugin in your environment. The Grafana team forwarded this [link](https://grafana.github.io/plugin-tools/docs/getting-started/), you can give it a try. If not, you can wait for an updated version as we have this in our pipeline.

Thanks,
Tanvi

**Comment by Zeevbd** [comment]
Hi Tanvi,
had some questions to the Grafana Tech support asking them for the solution estimation
and got the answer below:

can you kindly estimate how long will it take for the plugin to be built?
 
################################################
################################################

Hi Ze'ev,
I can see the plugin author is discussing this with  my plugin team in a separate ticket.
It isn't issue with Grafana but rather the plugin needed to comply with our build process.
**I believe it will take some time** but it is best to reach out to the Plugin Author to check with them on the plugin build.
 
-=-=-=-=-=-=-=-=-=-=-=-=-
Jay T.
Support Engineer
Grafana Labs
Need more help? Check out our docs page or visit our community forum:
https://grafana.com/docs/
https://community.grafana.com/
-=-=-=-=-=-=-=-=-=-=-=-=-

########################################################
########################################################

**Comment by tanvipise** [comment]
Hi,
Thanks for the update. We are in sync with the Grafana team for this. Will keep you posted!

**Comment by asimpson** [comment]
:wave: Hi @Zeevbd I looked into this and I think I understand how to get over this error. Since [building the plugin locally](https://github.com/vertica/vertica-grafana-datasource/issues/44#issuecomment-1634838839) you'll need to build the frontend (which you did via `yarn`) _and_ the [backend](https://grafana.com/docs/grafana/latest/developers/plugins/get-started-with-plugins/development-with-local-grafana/#run-your-plugin-in-development-mode).

The error message in question `gpx_vertica-grafana-plugin_darwin_arm64: no such file or directory` is referring the plugin's Go binary. You can build this binary by running `mage` from the root of the plugin directory (which you mentioned is `/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource`). `mage` should produce a binary file called `gpx_vertica-grafana-plugin_darwin_arm64` which should get rid of the error message you're seeing.

Let me know if that works! 🤞

**Comment by Zeevbd** [comment]
Hi @asimpson, thanks for chiming in.
looked into your suggestions and tried it.

did a fresh grafana installation 10.0.3
changed into the plugin directory and entered the "mage" command.

the message in response is that : **No .go files marked with the mage build tag in this directory**
will be glad to test any additional recommendation





<img width="916" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/ab4e033e-566e-4494-88fb-e984e537581e">

**Comment by asimpson** [comment]
@Zeevbd to clarify: are you attempting to `git clone` this repo and run it? or are you attempting to install the plugin through the Grafana plugin catalog?

For the former, you'll need to `git clone` this repo into your plugins directory and then run `mage`.

For the later, it should "just work" by installing the plugin via the Plugin UI.

**Comment by Zeevbd** [comment]
@asimpson,
cloned the repo into the plugin folder and ran the "mage" command

then went into the UI and installed the plugin...

the Results:
ARM64 file is missing after the "mage" command... and will not be able to use the plugin:

###################################################################
Commands and Results
###################################################################

❯ pwd
/opt/homebrew/var/lib/grafana/plugins
❯ git clone https://github.com/vertica/vertica-grafana-datasource/
Cloning into 'vertica-grafana-datasource'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 361 (delta 38), reused 32 (delta 16), pack-reused 280
Receiving objects: 100% (361/361), 23.13 MiB | 15.86 MiB/s, done.
Resolving deltas: 100% (157/157), done.
❯ ls -lrt
total 0
drwxr-xr-x@ 22 zeev.bd  admin  704 Aug 16 22:40 vertica-grafana-datasource
❯ cd vertica-grafana-datasource
❯ ls -lrt
total 1368
-rw-r--r--@  1 zeev.bd  admin   11357 Aug 16 22:40 LICENSE
-rw-r--r--@  1 zeev.bd  admin     324 Aug 16 22:40 Magefile.go
-rw-r--r--@  1 zeev.bd  admin   13142 Aug 16 22:40 README.md
drwxr-xr-x@  4 zeev.bd  admin     128 Aug 16 22:40 config
drwxr-xr-x@  3 zeev.bd  admin      96 Aug 16 22:40 coverage
-rw-r--r--@  1 zeev.bd  admin     438 Aug 16 22:40 go.mod
-rw-r--r--@  1 zeev.bd  admin   21892 Aug 16 22:40 go.sum
-rw-r--r--@  1 zeev.bd  admin     232 Aug 16 22:40 jest-runner-serial.js
-rw-r--r--@  1 zeev.bd  admin     877 Aug 16 22:40 jest.config.js
-rw-r--r--@  1 zeev.bd  admin    2246 Aug 16 22:40 package.json
drwxr-xr-x@ 11 zeev.bd  admin     352 Aug 16 22:40 pkg
drwxr-xr-x@ 22 zeev.bd  admin     704 Aug 16 22:40 src
-rw-r--r--@  1 zeev.bd  admin     326 Aug 16 22:40 tsconfig.json
-rw-r--r--@  1 zeev.bd  admin  619937 Aug 16 22:40 yarn.lock
❯ mage
❯ pwd
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource
❯ pwd
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource
❯ ls -lrt
total 0
❯ cd ..
❯ pwd
/opt/homebrew/var/lib/grafana/plugins
❯ ls -lrt
total 0
drwxr-xr-x@ 15 zeev.bd  admin  480 Aug 16 22:41 vertica-grafana-datasource
❯ cd  vertica-grafana-datasource
❯ ls -lrt
total 125128
-rw-r--r--@  1 zeev.bd  admin      3007 Aug 16 22:41 MANIFEST.txt
-rw-r--r--@  1 zeev.bd  admin      1733 Aug 16 22:41 plugin.json
-rwxr-xr-x@  1 zeev.bd  admin  11796480 Aug 16 22:41 gpx_vertica-grafana-plugin_linux_arm64
-rwxr-xr-x@  1 zeev.bd  admin  12378624 Aug 16 22:41 gpx_vertica-grafana-plugin_windows_amd64.exe
-rw-r--r--@  1 zeev.bd  admin     11357 Aug 16 22:41 LICENSE
-rw-r--r--@  1 zeev.bd  admin    541886 Aug 16 22:41 module.js
-rwxr-xr-x@  1 zeev.bd  admin  13230752 Aug 16 22:41 gpx_vertica-grafana-plugin_darwin_amd64
drwxr-xr-x@ 13 zeev.bd  admin       416 Aug 16 22:41 img
-rwxr-xr-x@  1 zeev.bd  admin  12374016 Aug 16 22:41 gpx_vertica-grafana-plugin_linux_amd64
-rw-r--r--@  1 zeev.bd  admin   1828149 Aug 16 22:41 module.js.map
-rwxr-xr-x@  1 zeev.bd  admin  11862016 Aug 16 22:41 gpx_vertica-grafana-plugin_linux_arm
-rw-r--r--@  1 zeev.bd  admin     13142 Aug 16 22:41 README.md
-rw-r--r--@  1 zeev.bd  admin      2510 Aug 16 22:41 module.js.LICENSE.txt
/opt/homebrew/v/li/g/pl/vertica-grafana-datasource stable ❯ ❯ pwd                                                               22:46:06
/opt/homebrew/var/lib/grafana/plugins
❯ git clone https://github.com/vertica/vertica-grafana-datasource/
Cloning into 'vertica-grafana-datasource'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 361 (delta 38), reused 32 (delta 16), pack-reused 280
Receiving objects: 100% (361/361), 23.13 MiB | 15.86 MiB/s, done.
Resolving deltas: 100% (157/157), done.
❯ ls -lrt
total 0
drwxr-xr-x@ 22 zeev.bd  admin  704 Aug 16 22:40 vertica-grafana-datasource
❯ cd vertica-grafana-datasource
❯ ls -lrt
total 1368
-rw-r--r--@  1 zeev.bd  admin   11357 Aug 16 22:40 LICENSE
-rw-r--r--@  1 zeev.bd  admin     324 Aug 16 22:40 Magefile.go
-rw-r--r--@  1 zeev.bd  admin   13142 Aug 16 22:40 README.md
drwxr-xr-x@  4 zeev.bd  admin     128 Aug 16 22:40 config
drwxr-xr-x@  3 zeev.bd  admin      96 Aug 16 22:40 coverage
-rw-r--r--@  1 zeev.bd  admin     438 Aug 16 22:40 go.mod
-rw-r--r--@  1 zeev.bd  admin   21892 Aug 16 22:40 go.sum
-rw-r--r--@  1 zeev.bd  admin     232 Aug 16 22:40 jest-runner-serial.js
-rw-r--r--@  1 zeev.bd  admin     877 Aug 16 22:40 jest.config.js
-rw-r--r--@  1 zeev.bd  admin    2246 Aug 16 22:40 package.json
drwxr-xr-x@ 11 zeev.bd  admin     352 Aug 16 22:40 pkg
drwxr-xr-x@ 22 zeev.bd  admin     704 Aug 16 22:40 src
-rw-r--r--@  1 zeev.bd  admin     326 Aug 16 22:40 tsconfig.json
-rw-r--r--@  1 zeev.bd  admin  619937 Aug 16 22:40 yarn.lock
❯ mage
❯ ls -lrt
total 0
❯ pwd
/opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource

########################################################
########################################################

**logs:**

logger=plugin.loader t=2023-08-16T22:41:52.237705+03:00 level=info msg="Plugin registered" pluginID=vertica-grafana-datasource
logger=plugin.loader t=2023-08-16T22:41:52.241619+03:00 level=error msg="Could not start plugin" pluginId=vertica-grafana-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/vertica-grafana-datasource/**gpx_vertica-grafana-plugin_darwin_arm64: no such file or directory"**
/



if the file: gpx_vertica-grafana-plugin_darwin_arm64  is not created, it will not work....

##################################################################
##################################################################
Waiting for Tanvi to create the missing file:

**Comment by Zeevbd** [comment]
Hi Tanvi...
any updates on the Driver?

Thanks
Ze'ev

**Comment by tanvipise** [comment]
Hi Ze'ev, this is going to take some time to resolve. I have uploaded my code to my [tpise](https://github.com/vertica/vertica-grafana-datasource/tree/tpise) branch in this repo, Grafana team is reviewing it for errors. We cannot guarantee a completion date as this is an open-source project where contributors are free to create any feature/bug fixes via submitting a PR.

**Comment by asimpson** [comment]
@Zeevbd sorry for being MIA for a bit. Your report is super strange to me, I've done the same steps on an M1 machine and the Darwin ARM binary was generated. 

Let's try something else :crossed_fingers: 

- In your `go.mod` file, change the version of the [grafana plugin sdk ](https://github.com/vertica/vertica-grafana-datasource/blob/040c4ce9d8276f6fccc0ee9deb078e2dc1e2947a/go.mod#L9)from `v0.86.0` to `v0.89.0`.
- Save that change and run `go mod tidy`.
- Run `mage`
- Check if the right darwin arm binary is generated in `dist`.

Hopefully this works. Please report back the results :pray: 

That's the earliest version that contained the [patch](https://github.com/grafana/grafana-plugin-sdk-go/pull/272) to build for darwin arm. It shouldn't cause any issues with your existing set up. The correct, long-term solution is to [upgrade the entire plugin to use the latest create plugin tools](https://grafana.com/developers/plugin-tools/migration-guides/migrate-from-toolkit), but this should at least get you out of this current jam.

**Comment by Zeevbd** [comment]
@asimpson thanks for responding back:
so i cloned the plugin again, followed your 4 bullet steps above and..

<img width="1506" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/73f04d4d-6d66-40e8-b4ee-e94eb4213f83">


got the needed file !!! encompassed in yellow.
now if i copy the file to the plugin directory, Grafana will lock the plugin as it was modified...

so i added the remark under  /grafana.ini file 
to:
allow_loading_unsigned_plugins = vertica-grafana-datasource
and restarted the service:

but the logs say that it would not load the plugin

logger=plugin.loader t=2023-09-02T10:37:16.450858+03:00 level=warn msg=**"Skipping loading plugin due to problem with signature"** pluginID=vertica-grafana-datasource status=modified

and the plugin on Grafana shows:

<img width="371" alt="image" src="https://github.com/vertica/vertica-grafana-datasource/assets/74586778/55ab2072-4eec-4105-8e1b-b7a49f7b99c2">


any idea how to bypass ? :)

**Comment by asimpson** [comment]
@Zeevbd great, that's progress!

That config line needs to be in the `[plugins]` [section](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/). 

Is that the case? Also what version of Grafana are you using again?

**Comment by Zeevbd** [comment]
@asimpson 
that is correct,
 the added line :

allow_loading_unsigned_plugins = vertica-grafana-datasource

is under [plugin ] section in grafana.ini

i have installed the latest version:
10.1.2 using : brew install grafana

**Comment by asimpson** [comment]
I just tested this on a new `git clone` and any changes from default settings I put in  [`conf/custom.ini`](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#macos) which I'll include in full here:

```ini
[log]
level = "debug"

[paths]
plugins = /home/adam/Projects/tmp/plugins

[plugins]
allow_loading_unsigned_plugins = vertica-grafana-datasource
```

And here's how it looks when I go to use the plugin:

![image](https://github.com/vertica/vertica-grafana-datasource/assets/1048831/10b90c59-abb0-4e82-8797-59011d7f1958)

Are there any differences with how I have things configured here with your config?

**Comment by Zeevbd** [comment]
have you copied the the file: gpx_vertica-grafana-plugin_darwin_arm64 to the plugin directory?

**and used the configuration:**. ?
[log]
level = "debug"

[paths]
plugins = /home/adam/Projects/tmp/plugins

[plugins]
allow_loading_unsigned_plugins = vertica-grafana-datasource

because on my machine the plugin was blocked

![image](https://github.com/vertica/vertica-grafana-datasource/assets/74586778/7be9717e-dc63-4595-a0ef-1ee410955b6d)

**Comment by asimpson** [comment]
Nope, the plugin directory is the parent directory which contains the plugin. The full path to the plugin is: 

`home/adam/Projects/tmp/plugins/vertica-grafana-datasource`

**Comment by Zeevbd** [comment]
Correct,
i was referring to the full path of the plugin directory, which is under the "vertica-grafana-datasource" directory.
after copying the new created  file: gpx_vertica-grafana-plugin_darwin_arm64 under the full path of the plugin directory i observed that the plugin changed to a "disabled" mode , like sent on the upper screen shot.

so how to your opinion can we proceed from this stage?

we have created the needed file: **_gpx_vertica-grafana-plugin_darwin_arm64_**
but now we need Grafana to recognize the modified plugin and able to work with it..

**Comment by asimpson** [comment]
> i was referring to the full path of the plugin directory, which is under the "vertica-grafana-datasource" directory.
after copying the new created file: gpx_vertica-grafana-plugin_darwin_arm64 under the full path of the plugin directory i observed that the plugin changed to a "disabled" mode , like sent on the upper screen shot.

You shouldn't copy the built binary anywhere. Move the entire `vertica-grafana-datasource` repo/directory under the plugins path. Run `mage` and `yarn build`. Restart Grafana, the plugin should no longer be disabled. 

If you hover on the `Disabled` message, is there a tooltip?

**Comment by Zeevbd** [comment]
The yarn build fails on dependencies


❯ yarn build
yarn run v1.22.19
warning package.json: "dependencies" has dependency "react-autosuggest" with range "^10.1.0" that collides with a dependency in "devDependencies" of the same name with version "^9.4.3"
error vertica-grafana-plugin@2.1.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"
error Commands cannot run with an incompatible environment.

**Comment by tanvipise** [comment]
Hi Ze'ev,

We have a new [version](https://github.com/vertica/vertica-grafana-datasource/releases/tag/v2.1.1) of the plugin released yesterday. It is verified and signed by Grafana. And it also has the binary distribution for M1 and M2 and we have tested it. Please feel free to check it out and let us know for any comments. I am closing this issue as it is fixed. 

Thanks,
Tanvi

**Comment by Zeevbd** [comment]
Hi Tanvi.
have downloaded and checked. It is perfectly working !!!

Thank you very much for the support and solution.
Ze'ev
